### PR TITLE
Sl/smart generated funcs

### LINKED ISSUE #22: make_function could create a smart @generated function
This would be especially useful for higher order approximations

### PR DESCRIPTION
**Pull request by sglyon**
main highlights:

-  closes #22 : smart generated functions that compute derivative expressions on the fly when the user asks for them
- remove `make_method` in favor of `make_function`, which has been given the smart generated function behavior 
- Allow users to pass mixed vectorized arguments.

### CODE REVIEW

**Comment by albop** [comment]
Have you seen the error message ?
Is it a problem with the test suite, or some more fundamental issue with the design ?

```
evaluating compiled code: Error During Test
  Test threw an exception of type ErrorException
  Expression: want ≈ @inferred(fun(Der{1}, V, p))
  eval cannot be used in a generated function
```

**Comment by sglyon** [comment]
I haven't seen that before, but I was able to figure out what is going wrong.

We aren't doing anything non-kosher in our code in Dolang. The issue is actually upstream with [calculus.jl calling `eval`](https://github.com/johnmyleswhite/Calculus.jl/blob/2806caa35659f8387813610dd09556db3e304142/src/symbolic.jl#L96) after doing a derivative. 

The easy way around this would be to just move to requiring SymEngine and dropping support for Calculus. Given that libsymengine is installed with Conda, this shouldn't be a problem except perhaps for users behind a firewall. Do you think this would be a problem at the bank?

**Comment by albop** [comment]
Yes, better not drop symengine. Can we just flag this test as known to fail ?

**Comment by sglyon** [comment]
Do you mean we shouldn't drop calculus?

We could instead put SymEngine in the `test/REQUIRE` file which would make sure it is available for CI, but not a requirement for users.

And this code would come with perceived regressions as users with Calculus.jl only would no longer be able to evaluate derivatives where they previously were. To get around this I can make sure the code we create contains "static" versions of first and second derivatives and then uses `@generated` for higher order. This loses some of the elegance of this solution, but would ensure that all existing code continues working

**Comment by albop** [comment]
But then we wouldn't test the system that users use...

So if I understand correctly what you're saying, Calculus is not working at all, so it is essentially incompatible with your PR. Is that right ?

**Comment by sglyon** [comment]
Hmm, good point. Hopefully users can be on symengine for performance reasons, but I understand that in some settings it isn't worth the headache.

So if I make the change I hinted at where I fully produce code for the first and second order derivatives when `make_function` is called and only rely on `@generated` for derivatives order 3 and higher then we will be able to use Calculus.jl for orders 0, 1, and 2 (e.g. what was implemented/available before this PR).

The issue is the combination of Calculus.jl and `@generated` because`@generated` functions cannot ever call `eval` and Calculus.jl does call `eval`.

**Comment by albop** [comment]
Yes, sorry for the pain. Maybe it's worth opening an issue against
Calculus.jl ?

**Comment by sglyon** [comment]
Sure, I can try to open an issue there.

So does that mean that in the short run (e.g. now) you are in favor of producing the orders 1 and 2 derivative code when `make_function` is called?

**Comment by sglyon** [comment]
How about this:

- Inside `make_function` if `Dolang.HAS_SYMENGINE` is true, then we can stick with the full `@generated` functions implemented in this PR.
- If `Dolang.HAS_SYMENGINE` then we will construct the code for orders 0, 1, and 2 and have `make_function` return it.

Then in the tests I will only test order 3 derivatives if `Dolang.HAS_SYMENGINE` is true.

That makes things a little less clean as code will branch based on dependencies, but it does allow us to preserve the best parts of each approach.

**Comment by sglyon** [comment]
Ok, I think we are good to go.

This PR now does the following:

- Regardless of backend, it allows for mixed-vectorized function calls (e.g. some arguments can be `AbstractVector` and will be implicitly repeated and others can be `AbstractMatrix`--one variable per column)
- If Calculus.jl is used as the differentiation backend, then `make_function` will generate code for the levels and derivatives order 1 and 2 -- this avoids the error we saw with `eval` above. This is the upper limit on what was possible before this PR, so all functionality is preserved.
- if SymEngine.jl as the differentiation backend then `make_function` will return a `@generated` function for all orders of derivative >= 0.

Tests pass on both 0.5 and 0.6 when Calculus.jl is used (as reported by CI) and on 0.5 and 0.6 with SymEngine (tested on my computer).

**Comment by albop** [comment]
Thank you again. I'll test how it works with Dyno then merge

**Comment by sglyon** [comment]
OK so I have added a little bit to this branch -- we now have docs.

See them live here: http://www.econforge.org/Dolang/

**Comment by albop** [comment]
@sglyon : this is really, really excellent. I had a look at the doc and it changes everything.
I'll merge now, and you can do a (pre)-release when you want.

**Comment by albop** [comment]
Honnestly, being able to compute higher order derivatives on-demand is super awesome. The model import is going to be much faster, even testing for the residuals.

**Pull request merged**
