### PR TITLE
Fix latex

### LINKED ISSUE #26: latex output fails with superscripts
According to the subscript/superscript conventions, latex("a__p1_p2(1)") should produce `a^{p1}_{p2,t+1}` but it fails with 
``` 
ERROR: BoundsError: attempt to access 0-element UnitRange{Int64} at index [0]
 in throw_boundserror(::UnitRange{Int64}, ::Int64) at ./abstractarray.jl:363
 in getindex at ./range.jl:478 [inlined]
 in _latex!(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Symbol, ::Void) at /home/pablo/.julia/v0.5/Dolang/src/printing.jl:61
 in _latex!(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Symbol) at /home/pablo/.julia/v0.5/Dolang/src/printing.jl:17
 in _latex!(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Expr) at /home/pablo/.julia/v0.5/Dolang/src/printing.jl:145
 in latex(::Expr) at /home/pablo/.julia/v0.5/Dolang/src/printing.jl:173
 in latex(::String) at /home/pablo/.julia/v0.5/Dolang/src/printing.jl:177
```
the printing.jl code does reference subscript/superscript suggests this was taken into account. @sglyon , any idea ?

### PR DESCRIPTION
**Pull request by sglyon**
Closes #26

### CODE REVIEW

**Comment by sglyon** [comment]
Hey @albop  do the tests in `tests/printing.jl` cover the main points? If not, could you add suggestions for other things we should be sure to test

**Comment by albop** [comment]
thank you. For the sake of safety you could add:
- `a_i_j__k(-1)` and `a_i_j__k(+1)`
Also, if already implemented we could have:
- `abar_xbar(1)` as well as `adot_xbar(1)` (we have bar on the python side, but not dot yet).

**Comment by sglyon** [comment]
Ok cool what would you expect `abar_xbar(1)` print to?

**Comment by albop** [comment]
`\overline{a}_{\overline{x}, t+1}`

**Comment by sglyon** [comment]
Great, thanks. I've added a handful more test cases.

Also I just added a commit that removed our dependence on a package MacroTools so that we don't need to `REQUIRE` it and we can get CI tests to pass. It doesn't really belong in this PR, but it is a minor change and helps us test our latex printing, so I figured I'd put it in here

**Comment by sglyon** [comment]
Should we merge this instead of closing?

**Comment by albop** [comment]
Yes. I really need to practice my button clicking skills !

**Pull request merged**
