### PR TITLE
Sl/make function

### PR DESCRIPTION
**Pull request by sglyon**
OK this has a lot of changes. They are roughly all isolated into separate commits, but somewhere in the middle changes were happening quickly and I didn't do a great job keeping commits separated.

Anyway, here's a list of what I did:

### Simplify FunctionFactory constructor

It no longer does validation. 

It only does the following:

- convert `lhs = rhs` to `rhs - lhs` if targets is not given
- normalizes the equations
- Normalizes targets. Before this was done later on in the compiler, now it is done here
- Creates in incidence table
- resolves all definitions (by direct substitution into equations)
- stores args, params, etc...

The validation code has been simplified and moved to a separate function
`validate!(::FunctionFactory)` if you still want to have Dolang do some
validation for you

### Extra helper functions in `symbolic.jl`

- `arg_name`: returns the variable name, throws away timing info
- `arg_time`: returns the timing info for a variable (defaults to 0), throws away the name
- Returns a tuple of `arg_name`, `arg_time`

These are used inside the compiler when compiling code for the derivatives.
They are used to extract variable name and time info so the incidence table can
be checked to see if a derivative wrt the variable at the given time is needed.

This makes the derivative code clean and extensible, **but** users will have to
extend this method if they want to differentiate w.r.t. more exotic symbol
types than `x::Symbol` and `x::{Tuple{Symbol,Int}}`. Not sure how you feel
about that... please comment.

### Smarter `normalize(::Symbol)`

In the past, `normalize(x::Symbol)` blindly returned `:_x_` for any `x`. Now it
is a bit smarter and only does the leading and trailing _ if `x` doesn't
already have them. This allows us to call `normalize(arg)` for any arg to make
sure we get the normalized version, without worrying about whether or not we've
already normalized it.

NOTE that this will probably require us to write some code in
Dolo/Dyno/dependencies that enforces users can't have variable names with
leading and trailing underscores.

### `make_function` function

This implements the `make_function` routine advertised in https://github.com/EconForge/Dolang/issues/24

### Other cleanup

- Some functions are no longer used anywhere, so I deleted them.
- IncidenceTable was moved to its own file in `src/incidence.jl`
- In all the tests we now have explicit timing for all variables. This created a lot of noise in the diffs for the tests, but isn't a big deal

### CODE REVIEW

**Comment by albop** [comment]
Thanks, this has solved the problem from yesterday. One little thing: while playing with the code I noticed `normalize(:(a=b))` yields `:(_b_-_a_)` while `normalize(:(a==b))` yields `:(_b_==_a_)`.
I find this behavior a bit risky and would prefer if we didn't rely on it. (it introduces a distinction in the semantics between `=` and `==` that we don't have in the yaml file, and can't actually support on python).

**Comment by albop** [comment]
In the same spirit we have in Dolo:

**Comment by albop** [comment]
In the same spirit this leads to a small bug in the generated code:


```
using DataStructures
eqs = [:(z=a+b*p)]
args = OrderedDict(:x=>[(:a,0)], :y=>[(:b,0)])
parms = [:p]
ff = Dolang.FunctionFactory(eqs, args, parms, targets=[:z])
code = Dolang.make_method(ff)
println(code)
```
the output contains `z_ = _a_ + _b_ * _p_`     which is fine

But:
```
eqs = [:(z==a+b*p)]
ff = Dolang.FunctionFactory(eqs, args, parms, targets=[:z])
code = Dolang.make_method(ff)
println(code) 
```
now the output has  `_z_ == _a_ + _b_ * _p_` which doesn't work

**Comment by albop** [comment]
Also we have in Dolo:
```
import Dolo.sanitize
Dolo.sanitize(:(a==b), [:a, :b])      #  :(a(0)==b(0))
Dolo.sanitize(:(a=b), [:a, :b])        #  :(a(0)==b(0))
```

**Comment by sglyon** [comment]
Would you prefer that we treat `a == b` in the same way we treat `a = b`?

And yes, in Dolo.jl we should make two changes:

1. Use sanitize too add explicit `(0)` before handing off to Dolang 
2. When extracting the targets we should build `[(variable, time)...]` instead of just `[variable...]`. The diff below does that

```
diff --git a/src/symbolic.jl b/src/symbolic.jl
index c77132e..fe50d81 100644
--- a/src/symbolic.jl
+++ b/src/symbolic.jl
@@ -145,9 +145,12 @@ function Dolang.FunctionFactory(sm::SymbolicModel, func_nm::Symbol)
     eqs = sm.equations[func_nm]

     # get targets
-    target = get(spec, :target, [nothing])[1]
-    has_targets = !(target === nothing)
-    targets = has_targets ? sm.symbols[Symbol(target)] : Symbol[]
+    target, shift = get(spec, :target, [nothing, nothing])[1:2]
+    if !(target === nothing)
+        targets = [(i, shift) for i in sm.symbols[Symbol(target)]]
+    else
+        targets = []
+    end

     # get other stuff
     args = Dolo._get_args(sm, spec)
```

**Comment by albop** [comment]
1. yes, I guess so.
2. OK, I'll make the fix in my WIP branch. I already have a workaround which does something equivalent.

**Comment by sglyon** [comment]
ok cool, I'll make normalize treat `=` and `==` in the same way

**Pull request merged**
